[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.6.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/xaque208/rftoy"

[[constraint]]
  name = "github.com/xaque208/things"
  version = "0.0.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

